### ISSUE TITLE
Bonjour/mDNS join in 0.18 

### ISSUE THREAD

**Issue by lukebigum** [choria-io/go-choria#1017]
As discussed on Slack, Choria 0.18 when running as a server is joining and leaving multicast DNS groups, even though HomeKit should not be enabled.

Config:
```
classesfile = /opt/puppetlabs/puppet/cache/state/classes.txt
collectives = all, ld4
identity = hostname.domain
logfile = /var/log/choria.log
loglevel = warn
main_collective = ld4
plugin.choria.agent_provider.mcorpc.agent_shim = /usr/bin/choria_mcollective_agent_compat.rb
plugin.choria.agent_provider.mcorpc.config = /etc/puppetlabs/mcollective/choria-shim.cfg
plugin.choria.agent_provider.mcorpc.libdir = /opt/puppetlabs/mcollective/plugins
plugin.choria.machine.store = /etc/choria/machine
plugin.choria.srv_domain = ld4.lmax
plugin.choria.status_file_path = /var/log/choria-status.json
plugin.choria.status_update_interval = 30
plugin.rpcaudit.logfile = /var/log/choria-audit.log
plugin.scout.overrides = /etc/choria/overrides.json
plugin.yaml = /etc/puppetlabs/mcollective/generated-facts.yaml
rpcaudit = 1
```

After starting `choria-server`, you can see it has opened a socket on mDNS:

```
[root@hostname.domain ~]# lsof -nPp $(pidof choria) | grep 5353
choria  159394 root    3u  IPv4 707650528      0t0       UDP *:5353 
```

It's very difficult to get a stack dump of it doing this, as it happens very early and very quickly.  An strace of the daemon shows that it opens this socket as one of the first thing it does, before opening a NATS connection or even reading it's own config file:

```
[pid 157502] 12:09:47.250085 bind(3, {sa_family=AF_INET, sin_port=htons(5353), sin_addr=inet_addr("0.0.0.0")}, 16 <unfinished ...>
[pid 157502] 12:09:47.250128 <... bind resumed> ) = 0
[pid 157502] 12:09:47.250167 epoll_ctl(4, EPOLL_CTL_ADD, 3, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=3995307800, u64=139680626741016}}) = 0
[pid 157505] 12:09:47.250216 <... epoll_pwait resumed> {{EPOLLOUT, {u32=3995307800, u64=139680626741016}}}, 128, 29, NULL) = 1
[pid 157502] 12:09:47.250245 getsockname(3,  <unfinished ...>
[pid 157505] 12:09:47.250255 epoll_pwait(4,  <unfinished ...>
[pid 157502] 12:09:47.250279 <... getsockname resumed> {sa_family=AF_INET, sin_port=htons(5353), sin_addr=inet_addr("0.0.0.0")}, [16]) = 0
...
[pid 157510] 12:09:47.268998 <... read resumed> "classesfile = /opt/puppetlabs/puppet/cache/state/classes.txt\ncollectives = all, ld4\nidentity = ldprof-live-mfix10.ld4.lmax\nlogfile = /var/log/choria.log\nloglevel = debug\nmain_collective = ld4\nplugin.choria.agent_provider.mcorpc.agent_shim = /usr/bin/choria_mcollective_agent_compat.rb\nplugin.choria.agent_provider.mcorpc.config = /etc/puppetlabs/mcollective/choria-shim.cfg\nplugin.choria.agent_provider.mcorpc.libdir = /opt/puppetlabs/mcollective/plugins\nplugin.choria.machine.store = /etc/choria/machine\nplugin.choria.srv_domain = ld4.lmax\nplugin.choria.status_file_path = /var/log/choria-status.json\nplugin.choria.status_update_interval = 30\nplugin.rpcaudit.logfile = /var/log/choria-audit.log\nplugin.scout.overrides = /etc/choria/overrides.json\nplugin.yaml = /etc/puppetlabs/mcollective/generated-facts.yaml\nrpcaudit = 1\n", 4096) = 824
```

Through a cruel twist of fate, this multicast DNS subscription / IGMP join is triggering some brief network interruption on some of our hardware whenever the daemon starts or stops.  To be fair, it's not Choria's fault, but it is might be the easiest one to change.

**Comment by ripienaar** [comment]
OK, I can see it now - I never saw it in my testing since as you say its so quick, but I can confirm that port is listening on my machines too.

Investigating I found:

https://github.com/brutella/dnssd/blob/5bf037ffaa398d044f05a31583ecd9aa60b04e1f/responder.go#L46

And that's what opens it, I'll have to reach out to the author there to see what we can do, failing that refactor some stuff and make a IoT specific choria build in addition to the one made for our server use cases - the IoT one would not include this stuff in any way.  Was planning to make these plugins anyway but not just yet, but thats a bit of an undertaking.

**Comment by ripienaar** [comment]
https://github.com/brutella/dnssd/issues/23

**Comment by ripienaar** [comment]
The upstream maintainer confirms the default port opening thing is an undesired feature and I made a PR to remove it, so hopefully next release will resolve this, else I'll make a private fork without the problem.

**Comment by ripienaar** [comment]
The default should be gone, bit of a temporary solution will keep an eye on the upstream to see what happens there.
