### ISSUE TITLE
Fact values comparison should be case insensitive

### ISSUE THREAD

**Issue by smortex** [choria-io/go-choria#1035]
Puppet variable comparison is case-insensitive, it's not unusual to see tests like `if $facts.get('os.family') == 'debian'` in a Puppet manifest, while the actual fact value is `Debian`.

When using mcollective (and now choria), the user has to keep in mind the variables case, `Debian` in the previous example:

```sh-session
romain@marvin ~ $ # Good examples:
romain@marvin ~ $ mco find -F os.family=Debian
romain@marvin ~ $ mco find -F os.family=FreeBSD
romain@marvin ~ $ mco find -F os.family=windows
romain@marvin ~ $ # Bad examples:
romain@marvin ~ $ mco find -F os.family=debian
romain@marvin ~ $ mco find -F os.family=freeBSD
romain@marvin ~ $ mco find -F os.family=Windows
```

By using case-insensitive string comparison, we can be more forgiving regarding these kind of inconsistencies with the end user.

**Comment by ripienaar** [comment]
very good, thank you :)
