### ISSUE TITLE
Wrong ping response time

### ISSUE THREAD

**Issue by fklajn** [choria-io/go-choria#1152]
My setup:
* choria version: 0.20.2
* 3 distributed choria-brokers with federation configured
Execution of `choria ping` gives results with ridiculous response times:
```
---- ping statistics ----
78 replies max: 9223372036854.777 min: 999999.000 avg: 9223372036854.764 overhead: -9223372036854.777
```
If I remove federation related lines from client config, the response times seem to be fine:
```
---- ping statistics ----
96 replies max: 183.611 min: 4.760 avg: 10.365 overhead: 84.087
```

**Comment by ripienaar** [comment]
We start the time calculation using the msg.OnPublish() method, but there are several issues:

 * We didnt call NotifyPublish() in federated or directed publishes
 * We didnt handle multiple calls to NotifyPublish() 

So what you're seeing is a case where the time wrapped round to negative.
