### ISSUE TITLE
Change in mco filter with choria

### ISSUE THREAD

**Issue by earthgecko** [choria-io/go-choria#1183]
There is some unexpected behaviour with the new version of choria using the mco command.

Running on CentOS 8 with:

```
rpm -qa | grep "puppet\|choria"
puppet6-release-6.0.0-14.el8.noarch
puppet-agent-6.21.1-1.el8.x86_64
choria-0.20.2-1.el8.x86_64
puppetserver-6.15.1-1.el8.noarch
```

It appears as if the `mco facts -F` filter is not working as expected.  If you filter the query with a non-existent fact, all the nodes are reported.

```
[tmp] mco facts -F with_a_fact_that_does_not_exist=true virtual
Report for fact: virtual  kvm found 9 times
Finished processing 9 / 9 hosts in 2.587s
[tmp] 
```

This is a change in behaviour since choria-0.19, the expected behaviour was if you filter with a fact that no node had, no nodes would report.
```
# choria-0.19
[~] mco facts region
Report for fact: region
  na found 1 times
  eu found 1 times
Finished processing 2 / 2 hosts in 2.244s
[~] mco facts -F region=eu virtual
Report for fact: virtual  kvm found 1 times
Finished processing 1 / 1 hosts in 2.135s
[~] mco facts -F region=none virtual
FATA[0002] Could not run Choria: no nodes were discovered
[~]
```

And the same behaviour on **really old** mcollective

```
[~] mco facts -F cloud=digitalocean hostname
No request sent, we did not discover any nodes.Report for fact: hostname
Finished processing 0 / 0 hosts in 0.00 ms
[~]
```

**Comment by ripienaar** [comment]
Ok, fixed this, sorry about that. Luckily a quick fix was worried the actual discovery system was broken :)

```
$ ./go-choria facts virtual -F foo=bar
FATA[0000] Could not run Choria: did not discover any nodes
```

Also as you use this in scripts you might be interested in recent addition of --json on this command (also --table is nice)
