### ISSUE TITLE
Build instructions and considerations

### ISSUE THREAD

**Issue by smortex** [choria-io/go-choria#134]
Hi!

I finally managed to build Choria on FreeBSD, the process was unexpectedly complicated, and I am not sure about the exactness of the process I used to build the code.

Because I have no real experience with go-based programs, I looked at other go software packages in the FreeBSD ports tree to see how they are built, and since there is a bunch of differences, it might make sense to consider a few points.

#### How I built choria

In case I did this utterly wrong, let me start by explaining how I built Choria:

```
git clone https://github.com/choria-io/go-choria
cd go-choria
go get
go build
```

This produced a working `go-choria` binary in the working directory \o/.

However, a `~/go` directory was created and a lot of source codes where downloaded there (I assume it's all the choria dependencies… 76MB :fearful:).

#### Reproducible builds

After creating a new user account and building choria the same way (but at a different date), the content of the `~/go` directory is not strictly the same (89 MB this time).  Maybe I am wrong, but my guess is that the dependencies are not fetch against a particular commit, and at some point, the build may break because of a dependency got updated.

In order to package Choria on FreeBSD, the checksum of all sources must be registered so that they are checked before building. Most go applications in the FreeBSD ports tree have all their dependencies included into their source code (!), generaly in a `vendor` directory (e.g. [aptly](https://github.com/smira/aptly/tree/master/vendor), [hub](https://github.com/github/hub/tree/master/vendor), [syncthing](https://github.com/syncthing/syncthing/tree/master/vendor), etc).  While this is arguably ugly, it offers the benefits of reproducibility.  Another option would be to add information about each dependencies version / commit, so that they could be checked.  This is for example done for the [go-cve-dictionary](https://svnweb.freebsd.org/ports/head/security/go-cve-dictionary/Makefile?revision=447954&view=markup#l24) port, based on a file [Gopkg.lock](https://github.com/kotakanbe/go-cve-dictionary/blob/master/Gopkg.lock) in upstream's repository (a lot more work for porters, but far less ugly at the repository level).

Moving into one of these directions (or something similar) would be awesome.

#### Binary name

The repository is called `go-choria`, and `go build` produce a `go-choria` binary. Can you confirm that the file should be renamed to `choria` when installed on the end-user system?

**Comment by ripienaar** [comment]
your build would be:

```
git clone https://github.com/choria-io/go-choria
cd go-choria
go get github.com/Masterminds/glide
glide install
go build .
```

though the actual build command in reality would be a lot more complex, along the lines of:

```
go build -o choria-0.0.4-linux-x86_64 -ldflags '-X github.com/choria-io/go-choria/build.Version=0.0.4 -X github.com/choria-io/go-choria/build.SHA=6eb2454 -X "github.com/choria-io/go-choria/build.BuildDate=2018-01-16 13:49:23 +0100" -B 0x77517c56757538dd3edc67eb9a304903'
```

**Comment by ripienaar** [comment]
`Gopkg.lock` is the new `go dep` system which while promising is a bit young to do what we need to do alas :(

**Comment by ripienaar** [comment]
And sorry yes, the binary should be `choria`, use `-o` as above to do what you want

**Comment by smortex** [comment]
Oh I see, glide installs to `~/go` and then populates the vendor director.  I failed to find this utility, thanks!

Running `~/go/bin/glide list` I see "Version not set for package" for each package.  Can I use the git commit listed in the generated `glide.lock` "safely" or now?

For now, the idea is to build Choria through the ports infrastructure.

**Comment by ripienaar** [comment]
hmm, not sure why it shows that but seems normal to me, yeah glide will install whats in the lock

I can of course release a FBSD binary if you like then its easier, but sure I get the desire for distro/OS to do their own builds :)

**Comment by smortex** [comment]
Okay, so I missed the fact that this lock file is actually in the repository :sweat_smile: 

I scripted the extraction of the relevant information and could build Choria successfully using the FreeBSD ports infrastructure. Thanks for the pointers!

The test ports is [available here](https://github.com/smortex/puppet5/commit/fc6d3b1bcca89a63cc8b222a2047e3fc259a021c), and will not be committed to the official ports tree until you consider it deserves a wider audience.

Closing since all my questions got answered :+1: Thanks

**Comment by ripienaar** [comment]
I put a comment on that link, how do you plan to run this? there's no init stuff?

**Comment by smortex** [comment]
> how do you plan to run this? there's no init stuff?

It's only usable in a FreeBSD context. We do have the ["ports tree"](https://www.freebsd.org/ports/) which is a set of Makefiles in a directory tree, where end-users can build and install software packages by `cd category/program && make install`.  The [puppet5 repository](https://github.com/smortex/puppet5) is the WIP repository for [FreeBSD's Puppet Team](https://wiki.freebsd.org/Puppet/) and is intended to be merged on top of the official FreeBSD ports tree.

So most of the build logic is shared in common files, and only the port-specific information has to be set in the Makefile.

**Comment by ripienaar** [comment]
Yeah, I used FreeBSD from 2.6 to iirc 7 or 8 days :) even employed freebsd committers.

But the question is Choria is a daemon and I do not see anything to run it in your repo or is it somewhere else that would start it

**Comment by smortex** [comment]
Oh, you mean "where is the rc-script?" :)  It's still to be written, but the hurry was to ensure it was building and running fine… which it did not before today.  So yes, I guess that now, it's the next step!
