### ISSUE TITLE
nats-io/go-nats dependency registered twice

### ISSUE THREAD

**Issue by smortex** [choria-io/go-choria#135]
I guess that the `nats-io/go-nats` dependency appears twice in `glide.lock`, first here:
https://github.com/choria-io/go-choria/blob/8352d2bf99b183bfe5b5f3a85f4e39b304fb0899/glide.lock#L46-L50

then here (with the name `nats-io/nats` that redirects to `nats-io/go-nats`):
https://github.com/choria-io/go-choria/blob/8352d2bf99b183bfe5b5f3a85f4e39b304fb0899/glide.lock#L55-L56

Notice how the second entry has the same commit as the first entry.

This was discovered while scripting dependencies extraction from glide.yaml.  I'll try to submit a PR that fix the issue.

**Comment by ripienaar** [comment]
The glide.lock file isnt maintained by hand, so we're not really going to be editing it :)

**Comment by smortex** [comment]
Yeah, I guess so… But the mistake seems to come from glide.yaml ;)

**Comment by ripienaar** [comment]
oh now I see thanks, `github.com/nats-io/go-nats` is not the same as `github.com/nats-io/nats` but github does a redirect thats why it happens, right we'll kill one

**Comment by ripienaar** [comment]
thanks! though now I note the mistake in the git commit.

The `(#nnn)` in a commit refers to the issue that opened it, not the PR, so your commit should have had `(#135)` not `(#136)`

**Comment by smortex** [comment]
Arf, I copied the issue number from the wrong tab, #134 instead of #135… I updated #136 for the records.
