### ISSUE TITLE
Allow 'choria discover' to be an inventory source while invoking 'choria rpc'

### ISSUE THREAD

**Issue by as0bu** [choria-io/go-choria#1352]
Currently, the output of `choria discover` cannot be used as an inventory source for `choria rpc`.

```
# choria discover -S '(!with("profiles::vault::agent") && with("os.release.major=6"))' -j | choria rpc puppet status
Discovering nodes using the flatfile method .... 0
FATA[0002] Could not run Choria: could not discover nodes: did not detect valid JSON data
```
This can be worked around by invoking an arbitrary rpc and leveraging that as an inventory source
```
# choria rpc -S '(!with("profiles::vault::agent") && with("os.release.major=6"))' shell run command='hostname' -j | choria rpc puppet status
Discovering nodes using the flatfile method .... 496

496 / 496    3s [================================================] 100%
<snip>
Summary of Applying:

   false: 479
    true: 17

Summary of Daemon Running:

   running: 493
   stopped: 3

Summary of Enabled:

    enabled: 483
   disabled: 13

Summary of Idling:

    true: 476
   false: 20

Summary of Status:

               idling: 465
   applying a catalog: 17
             disabled: 13
              stopped: 1


Finished processing 496 / 496 hosts in 10.482s
```
Thanks!

**Comment by ripienaar** [comment]
hmm, interesting, have you looked at `choria tool inventory` that can build files for inventory, and you can defined like named groups in it for like `-I group:el6_vault` if you do this often enough? 

For the example you show that might be quite hard to do right without being quite painful

**Comment by ripienaar** [comment]
```choria discover|choria req rpcutil ping --dm flatfile --do file=/dev/stdin```

**Comment by as0bu** [comment]
Thanks @ripienaar for that last example. I'll update our docs to capture that.
