### ISSUE TITLE
choria-server does not restart during package upgrade on Debian

### ISSUE THREAD

**Issue by smortex** [choria-io/go-choria#1388]
When upgrading choria on Debian, the `choria-server` service is not restarted (I could not check this for `choria-broker`).

So while the catalog applied successfully and no more change happen on subsequent runs of Puppet, the old service is still running and has to be restarted manually.

While we can probably do this in the puppet code to notify the service when the package is installed / upgraded, it feels like restarting the service also make sense for people using choria outside of a Puppet environment and should probably be fixed at the package level.

**Comment by ripienaar** [comment]
This would be based on the files here https://github.com/choria-io/go-choria/tree/main/packager/templates/debian

**Comment by ripienaar** [comment]
Specifically the generic/rules but I think by default this should be the case, we'll need someone who knows debian packaging I guess

**Comment by ripienaar** [comment]
yes - though broker off by default, but if enabled restart on upgrade.

I suspect this was not possible due to ancient ubuntu LTS constraints (systemd was very very new then), and now this can work well.  And we can ditch support for that old LTS entirely.

**Comment by smortex** [comment]
Yeah, make sense: restart any running service on upgrade, and if it's a new installation have these defaults:

Service       | Enable | Ensure
--------------|--------|---------
choria-broker | false  | stopped
choria-server | true   | stopped
