### ISSUE TITLE
Provide 64-bit ARM packages (arm64)

### ISSUE THREAD

**Issue by grandich** [choria-io/go-choria#1405]

**Comment by ripienaar** [comment]
For what distros?

**Comment by grandich** [comment]
We are interested in Ubuntu 20 (focal)

**Comment by ripienaar** [comment]
You can add these via a PR:

First we describe how to compile a binary

https://github.com/choria-io/go-choria/blob/8362ec405315d5f0e0a3f8776b93313a6b051ca9/packager/buildspec.yaml#L42-L46

Then we describe how to make debs:

https://github.com/choria-io/go-choria/blob/8362ec405315d5f0e0a3f8776b93313a6b051ca9/packager/buildspec.yaml#L176-L179

And you can then test locally using something like:

```
PACKAGES=xenial_64 rake build
```

Once you get that going send a PR and I'll do the integration with CircleCI and get nightlies built so we can test it

**Comment by ripienaar** [comment]
Please try https://apt.eu.choria.io/misc/choria_0.99.0.20220119_arm64.deb and see if that works for you? I dont have a proper deb repo for nightlies but this one been through the whole tool chain now so a manual test would be great.

Thanks for your help @ananace !

**Comment by ananace** [comment]
Just as a point of verification;
```console
root@pi-stack-3:/tmp# uname -m
aarch64
root@pi-stack-3:/tmp# cat /sys/firmware/devicetree/base/model; echo
Raspberry Pi 4 Model B Rev 1.1
root@pi-stack-3:/tmp# cat /etc/debian_version 
11.2
root@pi-stack-3:/tmp# curl -LO https://apt.eu.choria.io/misc/choria_0.99.0.20220119_arm64.deb 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 17.8M  100 17.8M    0     0  14.3M      0  0:00:01  0:00:01 --:--:-- 14.3M
root@pi-stack-3:/tmp# dpkg -i choria_0.99.0.20220119_arm64.deb 
(Reading database ... 59160 files and directories currently installed.)
Preparing to unpack choria_0.99.0.20220119_arm64.deb ...
Unpacking choria (0.99.0.20220119) ...
Setting up choria (0.99.0.20220119) ...
root@pi-stack-3:/tmp# choria --version
0.99.0.20220119
```

I don't have any 64-bit ARM systems on hand that I could rebuild to Ubuntu though, so I'm only able to verify the state of bullseye - but since it works there it _should_ just be a simple case of doing the same for Ubuntu.

**Comment by ripienaar** [comment]
thanks, yeah I think it will work for the lot of them, packaging is identical so thats good news.

Do you want to send in a update to add the rest (not needed for nightly, we can now remove from nightly)

**Comment by ripienaar** [comment]
Thank you @ananace
