### ISSUE TITLE
deleting a governor doesn't really delete it

### ISSUE THREAD

**Issue by WBasson** [choria-io/go-choria#1413]
Creating a governor that has never existed, creates it without prompting.
Deleting a governor, then showing it, reports the capacity as -1.
If you then re-create it,  you are prompted to override its settings, but if you have not yet tried reporting on it, it is created without a prompt.

**Comment by ripienaar** [comment]
Problem isn't delete - it does delete.  It's that view doesnt check if a governor is new and then creates a weird one instead of failing with not found.

**Comment by ripienaar** [comment]
```
$ choria governor view foo
FATA[0000] Could not run Choria: unknown governor
$ nats s ls --context choria.ams -j|grep foo
$
```
