### ISSUE TITLE
No way to list existing governors

### ISSUE THREAD

**Issue by WBasson** [choria-io/go-choria#1415]
It would be helpful if there was a 
choria governor list
or choria governor show --all
At the moment, asking to show a non-existent governor display it, and reports the capacity as -1.
This also seems to create one, because when you try to create a governor that was just reported as having a -1 capacity, you are prompted to override its settings, but if you have not yet tried reporting on it, it is created without a prompt.

**Comment by ripienaar** [comment]
```
$ choria governor ls
Known Governors:

        PUPPET
$ choria governor ls -j
[
  "PUPPET"
]
```
