### ISSUE TITLE
Running choria commands from cron no longer works

### ISSUE THREAD

**Issue by pebtron** [choria-io/go-choria#1433]
We recently upgraded choria from 0.20.2 to 0.23.0 and several of our cron jobs stopped working (Ubuntu 18.04 LTS). I determined the version that caused the breakage is 0.21.0. Sample cron:
`55 10 * * * USER=pebtron MCOLLECTIVE_CERTNAME=pebtron.mcollective choria facts -d location`
Generates this output:
```time="2021-09-20T10:55:01-05:00" level=debug msg="Logging at debug level due to CLI override"
time="2021-09-20T10:55:01-05:00" level=info msg="Enabling support for legacy SAN free certificates" component=security ssl=file
time="2021-09-20T10:55:01-05:00" level=debug msg="Puppet security system requesting legacy TLS support" component=security ssl=puppet
time="2021-09-20T10:55:01-05:00" level=debug msg="Forcing discovery mode to flatfile with Choria responses on STDIN" component=facts
time="2021-09-20T10:55:01-05:00" level=fatal msg="Could not run Choria: did not detect valid JSON data"
```

**Comment by ripienaar** [comment]
pass `--dm=mc`

I restored some behavior that was in `mco rpc` that lets it read discovery data from STDIN, but its hard to know the difference between cron and data on stdin, I suppose I could detect 0 bytes STDIN read - but its quite hard.  The above will work around while I think about it.

**Comment by pebtron** [comment]
Thank you for the fast response. The `--dm=mc` is working out of cron on both 0.21.0 and 0.23.0.

**Comment by ripienaar** [comment]
Closing in favor of https://github.com/choria-io/go-choria/issues/1732
