### ISSUE TITLE
Add support for RHEL9

### ISSUE THREAD

**Issue by mdechiaro** [choria-io/go-choria#1704]
This is a request to add support for rhel9 package in choria. Puppet supports this distribution as of version `7.14`. Thank you!

**Comment by ripienaar** [comment]
Would be helpful if you could install the el8 package on el9 and tell us if it works - I was reading the release notes early this week and it seemed that there wouldnt be much we would need to change, but worth a check

**Comment by mdechiaro** [comment]
Sounds good, I will install rhel8 package and test.

**Comment by ripienaar** [comment]
Give https://yum.uk.choria.io/nightly/el/9/x86_64/choria-0.99.0.20220602-1.el9.x86_64.rpm a try

**Comment by mdechiaro** [comment]
Thanks @ripienaar for the fast response on this request! I went ahead and tested the rhel9 nightly package, and it works. Here are some results.

Install
```
rpm -ivh https://yum.uk.choria.io/nightly/el/9/x86_64/choria-0.99.0.20220602-1.el9.x86_64.rpm
Retrieving https://yum.uk.choria.io/nightly/el/9/x86_64/choria-0.99.0.20220602-1.el9.x86_64.rpm
warning: /var/tmp/rpm-tmp.Q9k5kP: Header V4 RSA/SHA256 Signature, key ID 30fec20d: NOKEY
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:choria-0.99.0.20220602-1.el9     warning: /etc/choria/server.conf created as /etc/choria/server.conf.rpmnew
################################# [100%]
```

Status
```
systemctl status choria-server
* choria-server.service - The Choria Orchestrator Server
     Loaded: loaded (/usr/lib/systemd/system/choria-server.service; enabled; vendor preset: disabled)
     Active: active (running) since Thu 2022-06-02 13:10:25 CDT; 18s ago
   Main PID: 4300 (choria)
      Tasks: 9 (limit: 23561)
     Memory: 11.1M
        CPU: 810ms
     CGroup: /system.slice/choria-server.service
             `-4300 /usr/bin/choria server --config=/etc/choria/server.conf

Jun 02 13:10:25 hostname.domain.com systemd[1]: Started The Choria Orchestrator Server.
```

Query
```
choria discover -W os.name=RedHat -W os.release.major=9
hostname.domain.com
```

**Comment by ripienaar** [comment]
Great so we need some tweaks to the puppet modules I suspect - some PRs on those would be amazing

**Comment by mdechiaro** [comment]
I can help with getting this supported in `puppet-choria` module. It may take a few days to submit the PR.

**Comment by ripienaar** [comment]
I'll close this, it should be included in next release - module work to be done in other issues.
