### ISSUE TITLE
github.com/fatih/structtag missing ?

### ISSUE THREAD

**Issue by gedw99** [choria-io/go-choria#1874]
when building i am getting stuck at the gen phase... 

``` 
go get github.com/fatih/structtag
go: added github.com/fatih/structtag v1.2.0
go mod tidy
go build .
go generate ./...
2022/10/17 12:46:56 Generating plugin loaders from packager/plugins.yaml
2022/10/17 12:46:56 Generating loading code for plugin choria_data from github.com/choria-io/go-choria/providers/data/golang/choriadata into plugin_0_choria_data.go
2022/10/17 12:46:56 Generating loading code for plugin choria_provision from github.com/choria-io/go-choria/providers/agent/mcorpc/golang/provision into plugin_1_choria_provision.go
2022/10/17 12:46:57 Generating loading code for plugin choria_registry from github.com/choria-io/go-choria/providers/agent/mcorpc/golang/registry into plugin_2_choria_registry.go
2022/10/17 12:46:57 Generating loading code for plugin config_item_data from github.com/choria-io/go-choria/providers/data/golang/configdata into plugin_3_config_item_data.go
2022/10/17 12:46:58 Generating loading code for plugin exec_watcher from github.com/choria-io/go-choria/aagent/watchers/execwatcher into plugin_4_exec_watcher.go
2022/10/17 12:46:58 Generating loading code for plugin externalmco from github.com/choria-io/go-choria/providers/agent/mcorpc/external into plugin_5_externalmco.go
2022/10/17 12:46:59 Generating loading code for plugin file_watcher from github.com/choria-io/go-choria/aagent/watchers/filewatcher into plugin_6_file_watcher.go
2022/10/17 12:46:59 Generating loading code for plugin golangmco from github.com/choria-io/go-choria/providers/agent/mcorpc/golang into plugin_7_golangmco.go
2022/10/17 12:46:59 Generating loading code for plugin gossip_watcher from github.com/choria-io/go-choria/aagent/watchers/gossipwatcher into plugin_8_gossip_watcher.go
2022/10/17 12:47:00 Generating loading code for plugin homekit_watcher from github.com/choria-io/go-choria/aagent/watchers/homekitwatcher into plugin_9_homekit_watcher.go
2022/10/17 12:47:00 Generating loading code for plugin kv_watcher from github.com/choria-io/go-choria/aagent/watchers/kvwatcher into plugin_10_kv_watcher.go
2022/10/17 12:47:01 Generating loading code for plugin machine_data from github.com/choria-io/go-choria/aagent/data/machinedata into plugin_11_machine_data.go
2022/10/17 12:47:01 Generating loading code for plugin metric_watcher from github.com/choria-io/go-choria/aagent/watchers/metricwatcher into plugin_12_metric_watcher.go
2022/10/17 12:47:01 Generating loading code for plugin nagios_watcher from github.com/choria-io/go-choria/aagent/watchers/nagioswatcher into plugin_13_nagios_watcher.go
2022/10/17 12:47:02 Generating loading code for plugin rubymco from github.com/choria-io/go-choria/providers/agent/mcorpc/ruby into plugin_14_rubymco.go
2022/10/17 12:47:02 Generating loading code for plugin schedule_watcher from github.com/choria-io/go-choria/aagent/watchers/schedulewatcher into plugin_15_schedule_watcher.go
2022/10/17 12:47:03 Generating loading code for plugin scout from github.com/choria-io/go-choria/scout/agent/scout into plugin_16_scout.go
2022/10/17 12:47:03 Generating loading code for plugin scout_data from github.com/choria-io/go-choria/scout/data/scoutdata into plugin_17_scout_data.go
2022/10/17 12:47:04 Generating loading code for plugin timer_watcher from github.com/choria-io/go-choria/aagent/watchers/timerwatcher into plugin_18_timer_watcher.go
config/gen.go:23:2: no required module provides package github.com/fatih/structtag; to add it:
        go get github.com/fatih/structtag
main.go:4: running "go": exit status 1
```

**Comment by ripienaar** [comment]
Just do the go get it suggests you do. The dependency is only used by gen and not choria in general so it’s not in the go mod. But also you can do “go generate -run and plugin” which should do only what build needs

**Comment by gedw99** [comment]
Maybe I am missing something but I did the go get it suggests at the very start …

**Comment by ripienaar** [comment]
you ran `go mod tidy` after which again removed it - since the code doesnt require it.  `go mod tidy` would not consider the needs of `go generate`

**Comment by ripienaar** [comment]
You should also `go generate` before `go build`.  Suggest you just run `go generate -run plugin ` which wouldnt need that package so no go get needed

**Comment by ripienaar** [comment]
Worth exploring why you are building it though? There are a bit more to building choria than this and the Rakefile does the correct way which sets various build variables etc

**Comment by gedw99** [comment]
Ok thanks . Will try it out.

**Comment by gedw99** [comment]
Closing

**Comment by gedw99** [comment]
I am a rake files newbie. 

Will try to tease out what’s it doing and makefile it . Is there any change you would be doing it ?

**Comment by ripienaar** [comment]
I do t really use Make no :) I plan to move to https://magefile.org/ instead of this Rake file

**Comment by gedw99** [comment]
Oh amen - know mage well

**Comment by ripienaar** [comment]
Generally I don’t use the Rakefile but I know some other people do - which was why I asked what it is you were trying to do by building to understand what current needs are

**Comment by gedw99** [comment]
Ah sorry I did not answer.

got a project t where I need to do Ops on thousands of servers. I know nats so figured that choris is at least worth a play. 

I got really confused with the docs talking about MCO , as I know crap about about puppet. But I know NATS concepts .

**Comment by gedw99** [comment]
I don’t need to pixie boot them . They are provided with a Linux OS but then I need to “script” them on mass. Hope that helps a bit

**Comment by ripienaar** [comment]
The docs is essentially entirely geared to Puppet users. Consider it a distribution of Choria for Puppet users. So lots of mco etc. 

Choria itself doesn’t need it but it’s a bit of a chore to get there from tbe docs since that use case just isn’t so turnkey. 

I am doing some work now that will make the non puppet use case more turnkey eventually. 

As for NATS. Choria deliberately don’t expose it or build on a lot of NATS stuff since essentially it’s transport agnostic - at the moment mainly in theory rather than execution - but i want to be careful not to make it a NATS thing. 

If you want we can have a zoom next week to talk about it and if I think it can help you etc

**Comment by ripienaar** [comment]
> I don’t need to pixie boot them . They are provided with a Linux OS but then I need to “script” them on mass. Hope that helps a bit

Thanks, not exactly Choria's strong point but suppose it could be done - though without Puppet or the new turnkey non Puppet stuff - you have a big task ahead to make this work seamlessly.

**Comment by gedw99** [comment]
Hey @ripienaar 

sorry about missing this thread - too many things slamming me... 

Would love to do a zoom on this. Its very kind of you to offer.

telegram might be easiest way to organise: https://t.me/gedw99
