### ISSUE TITLE
Choria Server for Windows

### ISSUE THREAD

**Issue by feltra** [choria-io/go-choria#2069]
Is there any official repository where I can get the installer or the binaries for Windows ?

**Comment by ripienaar** [comment]
I used to build them but there doesn’t seem to be much interest so I stopped as it’s quite a pain.

**Comment by ripienaar** [comment]
Do you need a full msi or just a binary?

https://yum.eu.choria.io/scratch/Choria-0.27.0-windows-x86_64-windows.tgz

Above has the binary and if you install WiX Toolset v3.11 the `package.bat` in there will make you an msi.

I publish nightly windows binaries here https://yum.eu.choria.io/nightly/binaries/windows/

**Comment by feltra** [comment]
Thanks! this will be very helpful!
