### ISSUE TITLE
Choria server audit logs should have configurable permissions

### ISSUE THREAD

**Issue by treydock** [choria-io/go-choria#2077]
The Choria server audit logs should be able to be configured to something like mode 0640 and also set the group ownership to someone other than root.  This will allow tools like Vector or Splunkforwarder to collect the logs since those applications tend to run as unprivileged users.

**Comment by ripienaar** [comment]
Hmm, dont have any other place we configure file ownership/permissions, any suggestion for config file syntax?

I could make it not change it for existing files, I think thats probably the current behavior, so you could pre-create a file and it would keep that way

**Comment by treydock** [comment]
I was imaging doing this:

```
plugin.rpcaudit.logfile = /var/log/choria-audit.log
plugin.rpcaudit.logfile.group = vector
plugin.rpcaudit.logfile.mode = 0640
```

I would be happy to submit a patch, I am somewhat familiar with Go as I maintain large Prometheus deployments and write many of the exporters we use.

The idea of pre-creating the file would work so long as the log rotation doesn't re-create the file.  It looks like the default logrotate rule uses `copytruncate` so that should be fine.  The "tricky" part with the systems we are currently deploying is they are immutable so Puppet runs once at boot and then never again so Puppet can't fix permissions if they get messed up.  That's one reason I was thinking of modifying the code in Choria to enforce the permissions.

https://github.com/choria-io/go-choria/blob/daca201c3778bdc93f619f22e60740c4fa171718/providers/agent/mcorpc/audit/choria.go#L70

My idea was to use the configurable mode there and then some extra logic after that to check if the group defined exists, and if so change the group ownership.

**Comment by ripienaar** [comment]
You couldnt really put other user files in /var/log though unless they are pre-created and carefully kept there always (which copytruncate is ok with), but there's significant risk to the file being removed for any reason it cannot be recreated on its own.  So I imagined you'd move it elsewhere?

**Comment by treydock** [comment]
I'm not sure I follow?  Our goal is just to have choria-server, running as root, to chgrp the file to "vector" and essentially do "chmod g+r" or just set mode to 0640, so that Vector can read the file.  The file's user ownership will still be root and even if it wasn't, that shouldn't be an issue since Choria server runs as root.

We already use this approach with rsyslog:

```
-rw-r-----+  1 root     vector          2024519 Aug 16 18:48 secure
-rw-r-----+  1 root     vector          1009159 Aug 16 18:48 messages
```

Since rsyslog runs as root we are able to force the group ownership as unprivileged group and mode as group readable.

**Comment by ripienaar** [comment]
Ok thought you wanted to change the user - changing group would be fine (missed that in your earlier reply)
