### ISSUE TITLE
Support JSON logs for CLI

### ISSUE THREAD

**Issue by treydock** [choria-io/go-choria#2103]
The CLI for Choria should support JSON logging so that things like shipping those logs to Splunk can be done as valid JSON.

A new flag like `--log-json` can setup logrus to enable JSON logging.

**Comment by ripienaar** [comment]
Where do you use the CLI that logs would go to Splunk? cron jobs etc?

iirc without a tty it should log as json automatically

**Comment by treydock** [comment]
We are running the Choria client from inside Jenkins jobs that run inside Docker containers.  In Jenkins this is what errors look like:

```
time="2023-12-20T13:00:08-08:00" level=error msg="received an error from OMIT: You are not authorized to call this agent or action" component=facts
```

Similar commands on GCP VM instance run ad-hoc will produce this:

```
ERRO[0002] received an error from OMIT: You are not authorized to call this agent or action  component=facts
```

**Comment by ripienaar** [comment]
You could try setting `logfile` in the config to /dev/stdout or similar 

https://github.com/choria-io/go-choria/blob/b4efaa32f29727f6252cdb5f74a70fb1fed53b93/choria/framework.go#L481

**Comment by treydock** [comment]
I tried the following and that didn't change the behavior.

```
mcollective_choria::client_config:
  logfile: stdout
```
The above put the `logfile` into `/etc/choria/plugin.d/choria.cfg`.

I tried the below and still got same results:

```
mcollective::common_config:
  logfile: stdout
```

That put the `logfile` into `/etc/choria/client.conf`

In the container I run `choria tool config` and see this line:

```
                          logfile: stdout
```

Is there some other method to set the `logfile` or does the CLI maybe use a different code path?

**Comment by ripienaar** [comment]
well setting it to stdout specifically doesnt trigger the logic, you have to give it a file path, so /dev/stdout.

**Comment by treydock** [comment]
🤦 I got thrown off by this switch statement:

https://github.com/choria-io/go-choria/blob/b4efaa32f29727f6252cdb5f74a70fb1fed53b93/choria/framework.go#L486

Looks like setting this works:

```
mcollective::common_config:
  logfile: /dev/stdout
```

Since this is going into a client-only container, not going to affect choria servers.

**Comment by treydock** [comment]
I think I've seen this with other languages, but if I write to `/dev/stdout` and then do like `command > output.json` the contents of `output.json` are mangled:

```
$ choria facts agent_specified_environment  --json > output.json
$ cat output.json
<SNIP>
}
m OMIT: You are not authorized to call this agent or action","time":"2023-12-21T20:42:32Z"}
{"component":"facts","level":"error","msg":"received an error from OMIT: You are not authorized to call this agent or action","time":"2023-12-21T20:42:32Z"}
<SNIP>
```

What I'm seeing is the logs are coming at the end and the beginning of the logs are truncated.  If I run the above command without redirecting stdout to a file, there are no issues and the JSON logs come first followed by the JSON output.

**Comment by ripienaar** [comment]
Meh ok. Well hoped there was a work around. 

You could also tell the client to log to a file - which would be in json format 

anyway we can add a thing to force it. Was just trying to find a short cut.

**Comment by treydock** [comment]
I tried something like this:

```
sed -r 's/^logfile.*/logfile = output.json/g' /etc/choria/client.conf > ./client.conf
choria facts agent_specified_environment  --json --config client.conf
```

That produces a very limited file with none of the authorization errors or any of the actual JSON output.  I do see this:

```
{"level":"fatal","msg":"Could not run Choria: could not perform request: context deadline exceeded","time":"2023-12-21T21:18:43Z"}
```

If I remove the `--config` flag it works without issue.

Any suggestions on the type of change that's needed? I can help make it and test it on my end.  I wasn't sure if maybe like `--log-json` flag made sense in here: https://github.com/choria-io/go-choria/blob/b4efaa32f29727f6252cdb5f74a70fb1fed53b93/cmd/cmd.go#L79.

**Comment by ripienaar** [comment]
Any more logs without --json?

I imagine we'd need to add a new config flag like logformat that can take values `default` and `json`.  Then in https://github.com/choria-io/go-choria/blob/b4efaa32f29727f6252cdb5f74a70fb1fed53b93/choria/framework.go#L481 set the formatter for `stdout` and `stderr` cases if the config is set to `json`

**Comment by treydock** [comment]
```
$ choria facts agent_specified_environment  --config client.conf
```
That produces no output as expected cause the config has:

```
$ grep log client.conf
logfile = /home/tdockendorf/output.json
logger_type = console
loglevel = warn
```

The log entries are all things I never see at console when not using `logfile` in config:

```
$ cat output.json
{"component":"client","connection":"choria=readonly-team.choria-publisher","level":"warning","msg":"Initial connection to the Broker failed on try 1: dial tcp: lookup puppet on 169.254.169.254:53: no such host","time":"2023-12-21T22:07:10Z"}
{"component":"client","connection":"choria=readonly-team.choria-receiver0","level":"warning","msg":"Initial connection to the Broker failed on try 1: dial tcp: lookup puppet on 169.254.169.254:53: no such host","time":"2023-12-21T22:07:10Z"}
{"component":"client","connection":"choria=readonly-team.choria-receiver2","level":"warning","msg":"Initial connection to the Broker failed on try 1: dial tcp: lookup puppet on 169.254.169.254:53: no such host","time":"2023-12-21T22:07:10Z"}
{"component":"client","connection":"choria=readonly-team.choria-receiver1","level":"warning","msg":"Initial connection to the Broker failed on try 1: dial tcp: lookup puppet on 169.254.169.254:53: no such host","time":"2023-12-21T22:07:11Z"}
{"component":"client","connection":"choria=readonly-team.choria-receiver2","level":"warning","msg":"Initial connection to the Broker failed on try 2: dial tcp: lookup puppet on 169.254.169.254:53: no such host","time":"2023-12-21T22:07:11Z"}
{"component":"client","connection":"choria=readonly-team.choria-publisher","level":"warning","msg":"Initial connection to the Broker failed on try 2: dial tcp: lookup puppet on 169.254.169.254:53: no such host","time":"2023-12-21T22:07:11Z"}
{"component":"client","connection":"choria=readonly-team.choria-receiver0","level":"warning","msg":"Initial connection to the Broker failed on try 2: dial tcp: lookup puppet on 169.254.169.254:53: no such host","time":"2023-12-21T22:07:11Z"}
{"component":"client","connection":"choria=readonly-team.choria-receiver1","level":"warning","msg":"Initial connection to the Broker failed on try 2: dial tcp: lookup puppet on 169.254.169.254:53: no such host","time":"2023-12-21T22:07:12Z"}
{"component":"client","level":"error","msg":"could not connect: context deadline exceeded","time":"2023-12-21T22:07:12Z"}
{"level":"fatal","msg":"Could not run Choria: could not perform request: context deadline exceeded","time":"2023-12-21T22:07:12Z"}
```

Looks like it's not using the correct configs to find brokers?  We have middleware hosts specified in `/etc/choria/plugin.d/choria.cfg` as we haven't switched to SRV yet.

> set the formatter for stdout and stderr cases if the config is set to json

I'll get a PR opened next week.  Trying to build RPMs locally and it's failing:

```
internal/fs/templates.go:16:2: golang.org/x/text@v0.14.0: Get "https://proxy.golang.org/golang.org/x/text/@v/v0.14.0.zip": tls: failed to verify certificate: x509: certificate signed by unknown authority
```

Getting those kind of errors.  It could be the corporate firewall and VPN I have to use 🤷 

Command I used:

```
PACKAGES=el8_64 GOVERSION=1.20 rake build
```

**Comment by ripienaar** [comment]
That'll be it, the plugins.d loading is relative to the path of client.conf, so that stuff isnt loaded at all.

instead of client.conf add ./choria.conf locally and just set the logfile setting you wish to set, dont pass --config.  choria.conf will be applied over client.conf and you should get both plugins.d parsed and local log settings.

**Comment by ripienaar** [comment]
“Choria tool config” will show you what files are loaded and so forth there you would see it’s not loading the system wide plugins.d when passing a custom —config

**Comment by treydock** [comment]
Yep, setting `choria.conf` into workspace and only having like `logfile = choria.log` in that file is producing the desired results where stdout has the response and the `choria.log` has the error logs as JSON.
