### ISSUE TITLE
/etc/init.d/choria-broker should source /etc/profile

### ISSUE THREAD

**Issue by lukebigum** [choria-io/go-choria#215]
choria-0.0.11-1.el6.x86_64 on a CentOS 6 install, the broker dies on startup with this error:

`{"level":"fatal","msg":"Could not configure Choria: Could not initialize Choria: SSL setup is not valid, 1 errors encountered: SSL Directory does not exist: exec: \"puppet\": executable file not found in $PATH","time":"2018-03-16T17:11:53Z"}
`

Debugging the init script, the PATH is set to /sbin:/usr/sbin:/bin:/usr/bin.  With the AIO installer for Puppet 4, the extra _/opt/puppetlabs_ search path comes from _/etc/profile.d/puppet-agent.sh_ and so I believe this init script will need to source _/etc/profile_ to get the full list of paths.

I patched this into the start function and it appears to work fine afterwards (but it should probably be done at the top):

```
start() {
    [ -x $exec ] || exit 5
    [ -f $conffile ] || exit 6
    [ -d $confdir ] || exit 6

    . /etc/profile
```

I'd send you a PR but I'm running out the door.

**Comment by ripienaar** [comment]
While not fixed how you suggest this was addressed in https://github.com/choria-io/go-choria/issues/202 which should improve it for all ways of running choria. What do you think?

**Comment by lukebigum** [comment]
Oh right, I read that title and didn't join the dots to my issue.  That should be fine.
