### ISSUE TITLE
Native os.Hostname() calls may return a technically invalid hostname

### ISSUE THREAD

**Issue by JSP-GIHS** [choria-io/go-choria#217]
The two source files:

`srvcache/srvcache.go`
`choria/config.go`

Leverage the go "os" package for the os.Hostname() call. On systems that are configured with a non-fqdn Hostname this results in an invalid configuration for choria::broker resulting in a (subjectively)cryptic error message that the hostname PEM certificates do not exist in the Puppet ssl directory.

As per follow up comments in [Choria Users](https://groups.google.com/forum/#!topic/choria-users/qBkkti-tiSo)

Suggestion for correction: may need to be combined with a modification to /choria-io/puppet-choria to populate the broker.conf with the fqdn fact.

**Comment by ripienaar** [comment]
Resolved via https://github.com/choria-io/go-choria/pull/242 but with a incorrect first line in the commit
