### ISSUE TITLE
Debian 12 support

### ISSUE THREAD

**Issue by ananace** [choria-io/go-choria#2175]
Since Debian 10 is going fully EoL by the end of June, it might be a good idea to have choria packages ready for 12 sooner rather than later.

Shouldn't need more than a copy-paste of the other Debian packaging config.

**Comment by smortex** [comment]
Hey!  The latest release added support for Debian 12, I think we can close this issue.  In case you find problem, open an issue in the appropriate repo and feel free to mention me.

Thanks!
