### ISSUE TITLE
improve windows support

### ISSUE THREAD

**Issue by ripienaar** [choria-io/go-choria#281]
- [ ] do not log in color to the terminal
 - [ ] have a real configuration dir where config files go, now uses \etc...
 - [x] add a windows compatible service runner thing ([example](https://github.com/golang/sys/blob/master/windows/svc/example/service.go))

**Comment by ripienaar** [comment]
start with:

```
C:\Program Files\Choria\bin
     choria.exe
     choria.bat
     choria_mcollective_agent_compat.rb # from the module

C:\Program Files\Choria\log
     choria*.log

C:\ProgramData\Choria\
     server.conf
     broker.conf
```

**Comment by netdata-be** [comment]
Hi there, can I assist you with the windows support?
We spoke a CfgMgmtCamp last month, and would really like to get choria running for windows.

**Comment by ripienaar** [comment]
Hey, thanks a lot for the offer!

I am scheduled to start digging into what it means to get this going in a week or 3, let me get back to you?

Meanwhile I can try document how to build a windows binary and you can try it and see where things break and start opening issues around that? Then we just have to itterate till things are functional I think.

Apart from that I need to understand what would make sense for packing, a msi or chocolatey or is a msi a prereq for chocolaty etc?

**Comment by ripienaar** [comment]
```
% docker run -ti -v `pwd`:/tmp/base --rm choria/packager:el7-go1.10 bash
# yum -y install git
# mkdir -p /go/src/github.com/choria-io
# cd /go/src/github.com/choria-io/
# git clone https://github.com/choria-io/go-choria.git
# cd go-choria/
#  go get github.com/Masterminds/glide
# /go/bin/glide install
.....
[INFO]  Replacing existing vendor dependencies
# go generate
2019/02/25 16:32:16 Generating plugin loaders from packager/plugins.yaml
2019/02/25 16:32:16 Generating loading code for plugin golangmco from github.com/choria-io/mcorpc-agent-provider/mcorpc/golang into plugin_1_golangmco.go
2019/02/25 16:32:16 Generating loading code for plugin rubymco from github.com/choria-io/mcorpc-agent-provider/mcorpc/ruby into plugin_2_rubymco.go
# GOOS=windows GOARCH=amd64 go build
# ls -l go-choria.exe
-rwxr-xr-x 1 root root 20528128 Feb 25 16:32 go-choria.exe
# cp go-choria.exe /tmp/base
# exit
```

So this isn't pretty - I have a build system that would make this MUCH easier, but I realised there's a bug in it for supporting windows so above will get you a choria exe :)

**Comment by ripienaar** [comment]
OK I think I fixed that bug, so now:

```
$ git clone https://github.com/choria-io/go-choria.git
$ cd go-choria
$ go get github.com/Masterminds/glide
$ glide install
$ rake build_binaries
$ ls -l choria-0*
-rwxr-xr-x 1 root root 20018688 Feb 25 18:03 choria-0.0.0-darwin-amd64
-rwxr-xr-x 1 root root 18030985 Feb 25 18:02 choria-0.0.0-linux-386
-rwxr-xr-x 1 root root 20237071 Feb 25 18:02 choria-0.0.0-linux-amd64
-rwxr-xr-x 1 root root 20528128 Feb 25 18:03 choria-0.0.0-windows-amd64.exe
```

**Comment by smortex** [comment]
Regarding packaging, I was pleased to find that the GNOME project has a set of tools to build Windows Installers (.msi files) without the need of a windows machine ([msitools](https://wiki.gnome.org/msitools) upstream, split in multiple packages on Debian, including [wixl](https://packages.debian.org/buster/wixl) which is the one we are the most interested in).

I did some work to test this and quickly got something that works: https://github.com/smortex/go-choria/commit/a7f06150f2959681a9618abb1a519d0c8a712027

I guess some bits in the Rakefile are already done by `rake build_binaries` for users who can use docker ; and a lot of information in the XML file that describes the installation process is metadata which needs to be adjusted.  I do not feel legitimate to fill-in some of this information though (e.g. package comment, description and manufacturer).  If you think this direction is acceptable, feel free to either steal this code (I already stole it from the samples) or give directtion for the values you would like to see in these fields and I will fill-in a PR.

**Comment by ripienaar** [comment]
Interesting that approach can very easily fit into my build framework so it would all be driven by the buildspec.yaml, thanks for that I will take a peek

**Comment by ripienaar** [comment]
Lots have happened, I think the situation is at least bearable now.
