### ISSUE TITLE
unique logging between broker and server

### ISSUE THREAD

**Issue by lukebigum** [choria-io/go-choria#282]
Very low priority, but while figuring out what logs the new Go daemons were using I found several redundant files and one being used by both daemons.  

```
[root@puppet ~]# ps -fe | grep choria
root      4578     1 17 14:34 pts/1    00:07:01 /usr/sbin/choria broker --config=/etc/choria/broker.conf --pid=/var/run/choria-broker.pid
root     13737     1  0 13:27 ?        00:00:03 /usr/sbin/choria server --config=/etc/choria/server.conf --pid=/var/run/choria-server.pid
root     22106 22020  0 15:13 pts/1    00:00:00 grep choria
[root@puppet ~]# lsof -nPp 4578 | grep log
choria  4578 root    1w   REG    253,0        0 413589 /var/log/choria-broker
choria  4578 root    2w   REG    253,0        0 413589 /var/log/choria-broker
choria  4578 root    6w   REG    253,0      425 415020 /var/log/choria.log
[root@puppet ~]# lsof -nPp 13737 | grep log
choria  13737 root    1w   REG    253,0        0 415130 /var/log/choria-server
choria  13737 root    2w   REG    253,0        0 415130 /var/log/choria-server
choria  13737 root    6w   REG    253,0      425 415020 /var/log/choria.log
```

The duplicate open file handles to choria-broker and choria-server look like a mistake, unless it's a Go-ism?  Also should the default log location of different services be a different file?

**Comment by ripienaar** [comment]
hmm, those `choria-server` and `choria-broker` would be the output from the init scripts like incase of failure before any logging is setup on pre systemd unixen

https://github.com/choria-io/go-choria/blob/c06e411211e78238c896f2e1181946c84fa9e375/packager/templates/el/el6/server.init#L47

all the go written logs will be in JSON in the one log file and you can pick out which is which based on `"component":"server"` and `"component":"federation"` and `"component":"network_broker"` though some bits of logging seem to happen before that catagorisation is done.

I dont mind splitting them and tbh i am not really sold on the JSON format either but then I see things like https://github.com/rcoh/angle-grinder and I am again

**Comment by ripienaar** [comment]
https://github.com/choria-io/puppet-choria/commit/47458fecefdeaaed9899992417882e1bc8c35eea
