### ISSUE TITLE
alt_dns_names needed for AWS installations

### ISSUE THREAD

**Issue by ds2000** [choria-io/go-choria#415]
Hi,

As discussed this morning, AWS cluster instances for Choria brokers have dynamic hostnames.  Particularly with autoscaling / termination.  I have setup an alt_dns_names (puppetch) for the SRV record but we see this message when trying to connect to the NATs broker:

`"component":"server","connection":"eunlchosvr016","identity":" eunlchosvr016 ","level":"warning","msg":"Initial connection to the NATS broker cluster failed: x509: certificate is valid for eunltestch01, not puppetch","time":"2018-08-23T12:16:15+02:00"}`

and the puppet cert when queried:
```
puppet cert list --all |grep puppetch
+ " eunltestch01"            (SHA256) SDSdSDSDSDSdsDSDSDSDASDSADSAASDASD (alt names: "DNS: eunltestch01", "DNS:puppetch")

```
Sadly we have no access to dynamically update the SRV record but we can add cnames at boot.
For now, I'll switch to the servername for the SRV record and continue testing.

Thanks

Dave

**Comment by ripienaar** [comment]
do you mind showing this certificate using `openssl x509 -in x.pem -text` rather than what puppet shows?

Best I can tell from the code - they just pass this to the go libraries.  And those do appear to support alt names.  So its perplexing

**Comment by ripienaar** [comment]
I'm closing this, in other tickets we confirmed alt names are being read - though the docs might need a bit of a update on this and that's being worked on
