### ISSUE TITLE
Support disabling/ignoring caching

### ISSUE THREAD

**Issue by vjanelle** [choria-io/go-choria#476]
As discussed on slack, for the use case of short lived certificates, it might be advantageous to disable caching, or at the very least replace them with each observation.

**Comment by ripienaar** [comment]
This one is pretty simple, we add a new property under:

https://github.com/choria-io/go-choria/blob/d99b9a2dbbdfc4f1a880dff23e3b57dc7ae811bc/config/config.go#L83

Make a boolean called SecurityAlwaysOverwriteCache with `confkey:"plugin.security.always_overwrite_cache"` and `default:"false"`

And then we'll need a ticket in go-security as well to make the file security plugin use that.
