### ISSUE TITLE
Set environment variables in Rakefile for MCOLLECTIVE_CERTNAME

### ISSUE THREAD

**Issue by vjanelle** [choria-io/go-choria#508]
Not everyone has a username of `rip`.  This makes it harder to run `rake test` without pre-setting up environment variables.

Set the default expected `MCOLLECTIVE_USERNAME` in the Rakefile for ease of development.

**Comment by ripienaar** [comment]
thanks - aside this is a minor thing you can do this kind of thing without a ticket
