### ISSUE TITLE
choria-server not starting when puppet environment folder is missing.

### ISSUE THREAD

**Issue by marc-brou** [choria-io/go-choria#557]
Usually not a problem if using the default "production" environment as puppet agent rpm creates the /etc/puppetlabs/code/environments/production folder, but switching the agent to another puppet environment causes the choria-server service to fail to start with a single line in the log:
{"level":"fatal","msg":"Could not run Choria: Could not initialize Choria: could not set up security framework: exit status 1","time":"2019-03-12T18:13:35Z"}

Simple workaround is to create an empty folder on all the servers (/etc/puppetlabs/code/environments/<your_new_env>) but that seems counter intuitive as I would not expect environment folders to be required on the puppet agent side.
choria-server is probably not doing much with the folder either as it works fine with an empty folder, it just needs to exist.

**Comment by ripienaar** [comment]
It does invoke puppet to find things like where the ssl directory lives. So in that situation probably commands like puppet agent —configprint ssldir also fails?

**Comment by marc-brou** [comment]
Puppet agent does not seem to care that the local environment folder does not exist...
$ rmdir /etc/puppetlabs/code/environments/puppet6_upg_test/
$ puppet agent --configprint ssldir
/etc/puppetlabs/puppet/ssl

Puppet apply on the other hand does not like it...
$ puppet apply --configprint ssldir
Traceback (most recent call last):
	5: from /opt/puppetlabs/puppet/bin/puppet:5:in `<main>'
	4: from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/command_line.rb:77:in `execute'
	3: from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/command_line.rb:139:in `run'
	2: from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:370:in `run'
	1: from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application_support.rb:34:in `push_application_context'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/environments.rb:38:in `get!': Could not find a directory environment named 'puppet6_upg_test' anywhere in the path: /etc/puppetlabs/code/environments. Does the directory exist? (Puppet::Environments::EnvironmentNotFound)

**Comment by marc-brou** [comment]
Even with "loglevel = debug" in /etc/choria/server.conf, all I get in /var/log/choria.log is that fatal could not set up security framework log line, I don't even get the usual "Choria Server version 0.10.0 starting..." line :(

All I need to do to trigger the issue is to set something like:  "environment=dirdoesnotexist" in /etc/puppetlabs/puppet/puppet.conf and try to restart choria-server.

I was actually only able to figure out it was not starting because of the missing folder by running:
# strace -f /usr/sbin/choria server --config=/etc/choria/server.conf
 and noticing that one of the last thing it was doing was stat on the env folder and getting a (No such file or directory) so I created it and it was then able to start.

I am using those RPM versions:
choria.x86_64                        0.10.0-1.el7
puppet-agent.x86_64                  6.2.0-1.el7
I also reproduced with same versions but in el5 and el6.

Let me know if there is any other logs I can provide or test I can do to help.

**Comment by ripienaar** [comment]
ok, I'll do some more testing on this, even the vagrant demo thats now on el6 (thus choria server) all nodes start with default puppet install - which I now note does include this file:

```
% rpm -qf /etc/puppetlabs/code/environments/production
puppet-agent-5.4.0-1.el7.x86_64
```

so this is no doubt some puppet weird things, I'll investigate thanks

**Comment by ripienaar** [comment]
This is due to puppet apply above, when I need to ask puppet for a setting:

https://github.com/choria-io/go-choria/blob/54b6aecc23247fd6f3cea7c9f863b7e9d5fdde7a/puppet/puppet.go#L82

And this is called from:

https://github.com/choria-io/go-security/blob/b259ec5ee20647587b1f8a9b1316b333de4ce3ad/puppetsec/util.go#L14

We can confirm this is it if you set `plugin.choria.ssldir` to the puppet ssl dir this should not happen.

If that's the case I can't really fix it you will need to ask Puppet to fix it so it does not fail in that case - I can though improve the error message to make this easier.

**Comment by ripienaar** [comment]
still though:

```[root@c357c6e6ad4b /]# rpm -ivh http://yum.puppetlabs.com/puppet6/el/7/x86_64/puppet-agent-6.2.0-1.el7.x86_64.rpm
Retrieving http://yum.puppetlabs.com/puppet6/el/7/x86_64/puppet-agent-6.2.0-1.el7.x86_64.rpm
warning: /var/tmp/rpm-tmp.yhe67y: Header V4 RSA/SHA256 Signature, key ID ef8d349f: NOKEY
Preparing...                          ################################# [100%]
Updating / installing...
   1:puppet-agent-6.2.0-1.el7         ################################# [100%]
[root@c357c6e6ad4b /]# rm -rf /etc/puppetlabs/code/environments/production/
[root@c357c6e6ad4b /]# /opt/puppetlabs/bin/puppet apply --configprint ssldir
/etc/puppetlabs/puppet/ssl```

I cant reproduce

**Comment by ripienaar** [comment]
Oh I see - they must have special handling for `production` to not fail if it does not exist, its when you set a non `production` environment in the config that this fails.

So I wonder if I should pass --environment production when calling puppet apply?

**Comment by marc-brou** [comment]
I can confirm that adding "plugin.choria.ssldir=/etc/puppetlabs/puppet/ssl" to /etc/choria/server.conf allows the choria-server to start correctly.

With my "broken" environment folder setup, I have the following results:
"puppet apply --configprint ssldir" Fails and complains about the environment folder not being found.

"puppet apply --configprint ssldir --environment=production"   Works fine.
"puppet agent --configprint ssldir"  Also works fine, assuming that puppet agent knows not to care about the local environment folder.

I think you are right about them having special handling for environment=production, even if I remove the production folder, I can't get puppet apply to break.

**Comment by ripienaar** [comment]
OK, so I'll add `--environment production` to the command and our woes should in theory be over
