### ISSUE TITLE
nats-io/go-nats-streaming renamed to nats-io/stan.go

### ISSUE THREAD

**Issue by smortex** [choria-io/go-choria#595]
https://github.com/choria-io/go-choria/blob/5e7ffa8c90be7113a9ae269ec0cbdeb4f7d3a24f/glide.yaml#L32

The tooling I did to manage the dependencies of the upcoming FreeBSD port shows that this project was renamed to `github.com/nats-io/stan.go`.  I do not know if it's relevant to your workflow, and I saw similar problems being fixed in your code on a regular basis so though you would be interested in the information :wink:

**Comment by ripienaar** [comment]
It’s a shitshow unfortunately. They didn’t release many dependencies yet etc. Will try to fix next release. The whole thing was very badly managed.

**Comment by ripienaar** [comment]
This got done along the way
