### ISSUE TITLE
EL6 init scripts in wrong location

### ISSUE THREAD

**Issue by vjanelle** [choria-io/go-choria#652]
The init scripts for el6 are in the wrong location:

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/installation_guide/s1-boot-init-shutdown-run-boot

Need to move them from /etc/init.d to /etc/rc.d/init.d.

Additionally, this breaks my container environments for testing, since /etc/init.d is no longer a symlink to /etc/rc.d/init.d/

**Comment by ripienaar** [comment]
thanks
