### ISSUE TITLE
req subcommand: add option to require specifying a filter

### ISSUE THREAD

**Issue by snakeb1t** [choria-io/go-choria#687]
This avoids the issue where a user mistakenly sends a command to all hosts, rather than a filtered set of hosts.

**Comment by ripienaar** [comment]
Maybe better as a config option so all clients are sibject to it? And we add this feature to the rpc client lib?

**Comment by snakeb1t** [comment]
Yeah, I added a config option here: https://github.com/choria-io/go-config/issues/27

Didn't think about adding the feature to the rpc client lib, though. I was thinking this was more for human use than automation, which is why I was thinking of just adding it to `req` subcommand

**Comment by snakeb1t** [comment]
So if we implemented it in rpc client lib, it would be an option to `broadcast.Discover`? If that were the case, we wouldn't want the default to be true, so you would have to modify all current clients anyways, to pass the dopt in

**Comment by ripienaar** [comment]
Probably rather the mcorpc client, I am super weary of over engineering the core client.
