### ISSUE TITLE
Provide EL8 packages

### ISSUE THREAD

**Issue by ananace** [choria-io/go-choria#709]
Now that CentOS 8.0 is out, and RHEL 8.1 has been released too, perhaps it's time to start building EL8 versions of the Choria packages too?

**Comment by ripienaar** [comment]
out of curiuosity have you found the el7 ones to work?

**Comment by ananace** [comment]
We're currently installing choria-0.10.1-1.el7.x86_64 (because of internal repo sync reasons) across ~400 systems, and choria 0.12.1-1.el7.x86_64 on our puppetmasters, though we're still mostly using the old mcollective packaging as well.

**Comment by ripienaar** [comment]
Ah sorry I mean if you tried the el7 one on el8 and if it works :)

**Comment by ananace** [comment]
Well, I can install the RPM on there, and the server service will start if I do. Though at the moment the actual configuration and firewall aren't yet in place due to a lack of el8 work for our manifests, so I can't verify if it works, or if it just starts.

**Comment by ripienaar** [comment]
OK, I am a bit snowed under with work for kubecon but after I can poke at this, knowing its mainly a copy/paste job from el7 would help me

**Comment by sheijmans** [comment]
Installed el7 package today on el8 and puppet chroria modules worked.
Host could be foune and puppet run could be initiated.
https://groups.google.com/d/msg/choria-users/kzLj57FUj9g/ajLTnhM3BAAJ

**Comment by ripienaar** [comment]
should be good to go, will be on tonights nightly if it works  else I'll reopen here
