### ISSUE TITLE
RPM's published on packagecloud.io are not signed + repo file disables gpgcheck

### ISSUE THREAD

**Issue by steve--d** [choria-io/go-choria#790]
The repo published on packagecloud.io for choria does not contain signed RPM's and the .repo file has gpgcheck=0 (disabled).

Is this intentional, and are there plans to enable package signing? I believe you can sign with the same gpg key you are signing your repo with.

**Comment by ripienaar** [comment]
The repo is signed by package cloud and afaik they can’t also sign the packages. 

I upload these packages direct from CI so didn’t want to put any keys there. Guess I could do some manual work - but I also just hate everything to do with gpg with a fiery passion so been putting it off. 

No good reasons I know I have to do it but that’s why

**Comment by steve--d** [comment]
Generally speaking in a corporate environment it makes everyone feel a bit better knowing that the RPM's have been signed by a trusted package builder.

For instance in your example of building in CI workflow and posting packages to packagecloud, there is a possibility that the web hosting company could be compromised and packages posted containing malicious components. In this case as the consumer of these RPM's I would have no idea that the packages were in fact published by someone other than the maintainer. If they were signed (and I was enforcing gpg checking) then my deployment or upgrade process would fail, leading me towards an investigation.

I realize package signing isn't a bulletproof solution, and your keys could be compromised on your build server / service as well, its just one piece to a larger security puzzle.

**Comment by ripienaar** [comment]
Yeah I understand the why :) unfortunately the only option would be to build in CI, download and sign locally - which doesn’t actually decrease the attack surface. 

Sure it is something I should do I get it, big change in my side to build releases in an environment that’s reasonably isolated etc. 

Alternative is that I do currently publish all the tooling and building the packages locally for users is one command which would then be done in their controlled environment- sure it’s not a answer to the general case just pointing out where things are today.

**Comment by tbelway-cbn** [comment]
Are there current plans for package signing?

**Comment by ripienaar** [comment]
We are now serving packages from our own repos. The packages and the repos are signed. 

Since the most recent release. Package cloud will not get further updates. 

So I think we can close this

https://choria.io/blog/post/2021/09/22/september_releases/

**Comment by abotelho-cbn** [comment]
Love to hear it!

Would you happen to know the URLs for the yum repos?

Documentation still appears to point to packagecloud: https://choria.io/docs/deployment/broker/#package-repos

Cheers

**Comment by smortex** [comment]
@abotelho-cbn the repos where changed in the package recently:

https://github.com/choria-io/puppet-choria/commit/837818ba4c1944fd3af4f8d6fb53083ae3f42838#diff-d560a9f139bd4307712a77126c64522e1c686e2f85225c3739fac71c2226f16aR21

The doc might be outdated indeed, thank you for fixing it!

https://github.com/choria-io/website

**Comment by ripienaar** [comment]
yum.(eu|uk|us).choria.io

the modules will set you up of course they do it with http://mirrorlists.choria.io/

**Comment by smortex** [comment]
I think all issues and inconsistencies where addressed and do not exist anymore.

Closing.
