### ISSUE TITLE
Add Windows support for running Ruby code

### ISSUE THREAD

**Issue by smortex** [choria-io/go-choria#805]
With the work-in-progress to bring Choria to Windows nodes with Puppet 6, when running an action that involves ruby code, the execution fails with `Cannot start the Shim for Ruby action puppet#status: fork/exec C:/Program Files/choria/bin/choria_mcollective_agent_compat.rb: %1 is not a valid Win32 application.`.  

A workaround is to setup a wrapper for `plugin.choria.agent_provider.mcorpc.agent_shim` containing:

```bat
@"C:\Program Files\Puppet Labs\Puppet\puppet\bin\ruby.exe" "C:\Program Files\choria\bin\choria_mcollective_agent_compat.rb" %*
```

This is a bit hackish and not straightforward to implement in the puppet-choria module.  Maybe it's more suitable to always run `/full/path/to/configured/ruby /full/path/to/choria_mcollective_agent_compat.rb` instead of relying on the shebang?

**Comment by ripienaar** [comment]
Think this now work somehow
