### ISSUE TITLE
Defunct choria_mcollect processes

### ISSUE THREAD

**Issue by grandich** [choria-io/go-choria#842]
I'm noticing defunct processes related to timeout errors in choria.log

Still trying to figure out the cause of the timeouts, but wondering if the accumulation of defunct proceses (dozens of them in some servers) points to some kind of error processing bug

Restarting choria-server cleans the defunct processes

```
# cat /var/log/choria.log.1 
{"component":"server","identity":"icehouse-dev02.xx","level":"error","msg":"Request f32d9dcf95eb54738b4d3e65f6e6ab6d failed, discarding: Agent dispatcher for request f32d9dcf95eb54738b4d3e65f6e6ab6d exiting on 60s timeout","time":"2020-03-15T12:06:34-04:00"}
{"agent":"shellcmd","component":"server","identity":"icehouse-dev02.xx","level":"error","msg":"Cannot decode output from Shim for Ruby action shellcmd#runcmd: EOF","subsystem":"agents","time":"2020-03-15T12:06:34-04:00"}
{"component":"server","identity":"icehouse-dev02.xx","level":"error","msg":"Request 9ad2a95d05d4581781d7575a8c7552a1 failed, discarding: Agent dispatcher for request 9ad2a95d05d4581781d7575a8c7552a1 exiting on 60s timeout","time":"2020-03-16T00:06:33-04:00"}
{"agent":"shellcmd","component":"server","identity":"icehouse-dev02.xx","level":"error","msg":"Cannot decode output from Shim for Ruby action shellcmd#runcmd: EOF","subsystem":"agents","time":"2020-03-16T00:06:33-04:00"}
{"component":"server","identity":"icehouse-dev02.xx","level":"error","msg":"Request b77178671c46597aa4499a1fc11ee98f failed, discarding: Agent dispatcher for request b77178671c46597aa4499a1fc11ee98f exiting on 60s timeout","time":"2020-03-16T01:16:34-04:00"}
{"agent":"shellcmd","component":"server","identity":"icehouse-dev02.xx","level":"error","msg":"Cannot decode output from Shim for Ruby action shellcmd#runcmd: EOF","subsystem":"agents","time":"2020-03-16T01:16:34-04:00"}  

# ps -HAo pid,lstart,cmd | sort -k6n -k3M -k4n -k5| egrep [d]efu | tail -3
16687 Sun Mar 15 12:05:34 2020     [choria_mcollect] <defunct>
14464 Mon Mar 16 00:05:33 2020     [choria_mcollect] <defunct>
28195 Mon Mar 16 01:15:34 2020     [choria_mcollect] <defunct>

# cat /etc/issue
Ubuntu 18.04.1 LTS \n \l

# dpkg -l choria*
ii  choria                                          0.13.1                       amd64                        The Choria Orchestrator Server and Broker         

```

**Comment by grandich** [comment]
it is an ancient "shellcmd" agent based on this one: https://github.com/example42/puppet-mcollective/blob/master/files/plugins/agent/shellcmd.rb

**Comment by ripienaar** [comment]
I'd avoid this :) the pattern combined with choria/mco is just bad. The one we have in the plugins repo is much more suited to the design of choria - but its a bit more awkward to use

**Comment by grandich** [comment]
We use a modified version of that plugin basically because it colorizes with red any stderr output and commands whose exit code is not zero, and it prefixes each output line the hostname (useful for redirections to grep)

We can program it from scratch, but in the meantime, is there any part of it we can enhance to avoid this timeout mishandling?

**Comment by ripienaar** [comment]
Unfortunately the only answer is to not take longer than timeout. Simple as that. 

The shell plugin we have runs commands in the background and let you comeback later to get the output. 

I agree this should not be happening. However I can guarantee you a shell plugin like what you describe is a bad idea with choria/mcollective. It’s not designed for that use case.

**Comment by ripienaar** [comment]
I saw a few of these for some other agent:

```
root     31335  0.0  0.0      0     0 ?        Z    Jul01   0:00 [choria_mcollect] <defunct>
```

Which was probably this request:

```
{"timestamp":"2020-06-30T23:57:50.283464+0000","request_id":"cd35555cf82254cf826a34567d8f3596","request_time":1593561470,"caller":"choria=typhon.mcollective","sender":"example.net","agent":"iptables","action":"block","data":{"ipaddr":"59.152.237.118","process_results":false}}
```

So something is definitely going on with timeouts and old agents

**Comment by ripienaar** [comment]
I did some tweaks here to make sure I wait() in a few more situations, seems to behave better but will run it locally for a while
