### ISSUE TITLE
install choria in the bin, not the sbin directory

### ISSUE THREAD

**Issue by smortex** [choria-io/go-choria#852]
The choria package currently installs `choria(1)` as `/usr/sbin/choria`.

This initially made sense because the choria binary as only a server component.  But recently, choria gained client capabilities (e.g. `choria req`) and regular users usually do not have `/usr/sbin` directory in their `$PATH`, making the `choria` harder to find by new users.

The packaging of choria should rather install choria as `/usr/bin/choria`.

**Comment by ripienaar** [comment]
```
% which choria
/sbin/choria
% sudo puppet agent --test
Notice: /Stage[main]/Choria::Install/Package[choria]/ensure: ensure changed '0.99.0.20200323-1.el7' to '0.99.0.20200409-1.el7'
% which choria
/bin/choria
% ps -auxw|grep choria
root     12349  1.0  0.1 923980 15720 ?        Ssl  11:45   0:00 /usr/bin/choria server --config=/etc/choria/server.conf
```

good stuff
