### ISSUE TITLE
improve windows packages

### ISSUE THREAD

**Issue by ripienaar** [choria-io/go-choria#857]
The Unix packager for wix is a bit meh, its not the real thing.

So we should for the moment prepare a artifact that has a batch file to run that makes the msi until we can automate this step too, but the msi compile should happen on windows.

 - [x] Add logos and banners
 - [x] Fix upgrade support
 - [x] Show the license
 - [ ] Automate via appveyor

**Comment by ripienaar** [comment]
welcome and license dialog

![](https://i.imgur.com/kC0Tfp6.png)

installer progress

![](https://i.imgur.com/u3FjHt2.png)

supports unattended installs via msiexec

**Comment by feltra** [comment]
where can I download the windows package ?
