### ISSUE TITLE
Provide ARM packages

### ISSUE THREAD

**Issue by smortex** [choria-io/go-choria#907]
ARM packages could be handy :tada:

**Comment by ripienaar** [comment]
@smortex how we're doing here? happy with the outcome? I am looking to do a release in the next day or 2, we should wire things up for release

**Comment by smortex** [comment]
Yes!  Amazing :heart_eyes:!  Let's adjust this to distribute releases and stop daily distribution of nightlies (unless it's useful to someone else?)  Stay tuned!

**Comment by ripienaar** [comment]
yeah we can drop the nightlies, did them just for your testing

**Comment by ripienaar** [comment]
thank you :)
