### ISSUE TITLE
Restart of Choria Agent failed on post provisioning in windows

### ISSUE THREAD

**Issue by srikanthtns** [choria-io/go-choria#913]
Once the choria agent provisions the configuration using a custom provisioner , the agent doesnt restart on a windows platform . Request to provide support to windows as linux does.

**Comment by ripienaar** [comment]
The problem with any other approach is that the service manager will not notice that there's now a new choria service and it might start a 2nd or future shutdowns wont work

So question: can you please test that if the choria just exits like if you kill it does the windows service manager restart it later on its own or does it stay down.

**Comment by srikanthtns** [comment]
Hi Arri

This is what I did for windows yday. The provisioner will shutdown the
choria service when config is updated. There will be scheduler that runs
every min to see if choria-service is up or not and start it if required.
Seems to work fine.

Thanks
Srikanth

**Comment by ripienaar** [comment]
Hmm not really a generic approach. But I guess I will add a option that the server just exit once provisioned for the situation where a supervisor is

Thanks

**Comment by ripienaar** [comment]
Can you try edit the choria.wxs file:

```xml
<ServiceInstall Id="{{cpkg_name}}ServerService" Name="{{cpkg_name}}-server" ErrorControl="normal" Interactive="no" Start="auto" Type="ownProcess" Arguments='server run --config "C:\ProgramData\{{cpkg_name}}\{{cpkg_etcdir}}\server.conf"' />
```

Turn this into:

```xml
<ServiceInstall Id="{{cpkg_name}}ServerService" Name="{{cpkg_name}}-server" ErrorControl="normal" Interactive="no" Start="auto" Type="ownProcess" Arguments='server run --config "C:\ProgramData\{{cpkg_name}}\{{cpkg_etcdir}}\server.conf"' >
<util:ServiceConfig
        FirstFailureActionType='restart'
        SecondFailureActionType='restart'
        ThirdFailureActionType='restart'            
        RestartServiceDelayInSeconds='30'
        ResetPeriodInDays='1'/>
</ServiceInstall>
```

Also at the top change:

```xml
<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
```

to

```xml
<Wix
  xmlns="http://wixtoolset.org/schemas/v4/wxs"
  xmlns:util="http://wixtoolset.org/schemas/v4/wxs/util"
  >
```

or 

```xml
<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi"      
  xmlns:util="http://schemas.microsoft.com/wix/UtilExtension">
```

if that gives errors.  Then after installing this wsi you can check in service properties it should be set to auto restart.

This is better than crons, this way it works for everyone out the box

**Comment by srikanthtns** [comment]
Sure , let me try . Thanks Arri.
